package lt.vu.mybatis.dao;

import java.util.List;

import lt.vu.mybatis.model.Player;
import org.mybatis.cdi.Mapper;


@Mapper
public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *
<<<<<<< HEAD
     * @mbg.generated Wed Apr 15 18:51:54 EEST 2020
=======
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
>>>>>>> d1d1ff6... Initial commit
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *

     * @mbg.generated Wed Apr 15 18:51:54 EEST 2020

     */
    int insert(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER

     *
     * @mbg.generated Wed Apr 15 18:51:54 EEST 2020

    Player selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *

     * @mbg.generated Wed Apr 15 18:51:54 EEST 2020

    List<Player> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYER
     *

     * @mbg.generated Wed Apr 15 18:51:54 EEST 2020

    int updateByPrimaryKey(Player record);
    */
}