package lt.vu.mybatis.model;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.ORDER_PLACED
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private String orderPlaced;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.CLIENT_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ORDERS.PART_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private Integer partId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.ID
     *
     * @return the value of PUBLIC.ORDERS.ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.ID
     *
     * @param id the value for PUBLIC.ORDERS.ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.ORDER_PLACED
     *
     * @return the value of PUBLIC.ORDERS.ORDER_PLACED
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public String getOrderPlaced() {
        return orderPlaced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.ORDER_PLACED
     *
     * @param orderPlaced the value for PUBLIC.ORDERS.ORDER_PLACED
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setOrderPlaced(String orderPlaced) {
        this.orderPlaced = orderPlaced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.CLIENT_ID
     *
     * @return the value of PUBLIC.ORDERS.CLIENT_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.CLIENT_ID
     *
     * @param clientId the value for PUBLIC.ORDERS.CLIENT_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ORDERS.PART_ID
     *
     * @return the value of PUBLIC.ORDERS.PART_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public Integer getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ORDERS.PART_ID
     *
     * @param partId the value for PUBLIC.ORDERS.PART_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setPartId(Integer partId) {
        this.partId = partId;
    }
}