package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

public class Part {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.NAME
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.TYPE
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.SUPPLIER_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    private Integer supplierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.ID
     *
     * @return the value of PUBLIC.PART.ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.ID
     *
     * @param id the value for PUBLIC.PART.ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.NAME
     *
     * @return the value of PUBLIC.PART.NAME
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.NAME
     *
     * @param name the value for PUBLIC.PART.NAME
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.TYPE
     *
     * @return the value of PUBLIC.PART.TYPE
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.TYPE
     *
     * @param type the value for PUBLIC.PART.TYPE
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.SUPPLIER_ID
     *
     * @return the value of PUBLIC.PART.SUPPLIER_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.SUPPLIER_ID
     *
     * @param supplierId the value for PUBLIC.PART.SUPPLIER_ID
     *
     * @mbg.generated Mon Apr 20 19:04:08 EEST 2020
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    @Getter @Setter
    private Supplier supplier;
}